
baseurl: ""
url: "https://triathlon.com"

# контакты
contact_phone: +7 912 123 45 00
contact_email: test@test.ru

contact_social_facebook: https://facebook.com
contact_social_instagram: https://www.instagram.com/triatlon_goldnik
contact_social_youtube: https://www.youtube.com/channel/UCUXyZhKmxe-21xOnhqbWFjg

github: https://github.com/semenovem/triathlon

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed

kramdown:
  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#  css_class: 'highlight'

#sass:
#  style: :expanded

# Exclude from processing.
exclude: [
  '.idea/',
  'node_modules', '_scripts', '_dev',
  'README.md', 'DEV_GUIDE.md',
  'gulpfile.js', 'package.json', 'package-lock.json', 'yarn.lock',
  'LICENSE',
  '.editorconfig'
]

collections:
  coach:
    output: true
  report:
    output: true

defaults:
  - scope:
      path: ""
      type: coach
    values:
      layout: coach
      nav_light: COACHES
  - scope:
      path: ""
      type: report
    values:
      layout: report
      nav_light: REPORTS

# hash commit, for prevent caching file resource
short_hash_commit:

#end
