
baseurl: ""
url: "https://azbukatriathlona.com"

# контакты
contacts:
  phone: +7 926 333 28 99
  email: test@test.ru
  social:
    instagram:
      url: https://www.instagram.com/triatlon_goldnik
      alt: Мой instagram
    youtube:
      url: https://www.youtube.com/channel/UCUXyZhKmxe-21xOnhqbWFjg
      alt: Мой канал на youtube

github: https://github.com/semenovem/triathlon

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed

kramdown:
  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#  css_class: 'highlight'

#sass:
#  style: :expanded

# Exclude from processing.
exclude: [
  '.idea/',
  'node_modules', '_scripts', '_dev',
  'README.md', 'DEV_GUIDE.md',
  'gulpfile.js', 'package.json', 'package-lock.json', 'yarn.lock',
  'LICENSE',
  '.editorconfig'
]

collections:
  coach:
    output: true
  report:
    output: true

defaults:
  - scope:
#      path: "coach/*/index.html"
      type: coach
    values:
      layout: coach
      nav_light: COACHES

  - scope:
#      path: "report/*/index.html"
      type: report
    values:
      layout: report
      nav_light: REPORTS

  - scope:
      path: ""
#      path: "*/index.html"
    values:
      yandexMetrika: true

# hash commit, for prevent caching file resource
short_hash_commit:

array: []

#end
